tensorflow/tpu

README.md
cloud_tpu/models/mnist/mnist.py
cloud_tpu/models/resnet/estimator_resnet.py
cloud_tpu/models/resnet/layers_resnet.py
cloud_tpu/models/resnet/vgg_preprocessing.py

Merge internal changes into public repository

---

cloud_tpu/models/inception_v3/inception_v3.py

xrange() is called on line 256.

from six.moves import xrange

---

cloud_tpu/datasets/imagenet_to_gcs.py
cloud_tpu/models/alexnet/alexnet.py
cloud_tpu/models/census/census.py
cloud_tpu/models/cifar/cifar.py
cloud_tpu/models/inception/inception_v2.py
cloud_tpu/models/inception/inception_v3.py
cloud_tpu/models/magenta/melody_rnn_train.py
cloud_tpu/models/mnist/mnist.py
cloud_tpu/models/movielens/movielens.py
cloud_tpu/models/ptb/ptb.py
cloud_tpu/models/resnet_garden/resnet_main.py

Merge internal changes into public repository (change 173133218)

---

tools/datasets/imagenet_to_gcs.py

Shuffle training and validation data when creating tfrecords.

Merge internal changes into public repository (change 188401932)

---

models/experimental/resnet_bfloat16/resnet_main.py
tools/ctpu/config/config.go
tools/ctpu/config/config_test.go

Merge internal changes into public repository (change 189235869)

---

models/experimental/amoeba_net/amoeba_net_model.py
tools/ctpu/config/config.go
tools/ctpu/config/config_test.go
tools/ctpu/main.go

Merge internal changes into public repository (change 202324411)

---

models/experimental/amoeba_net/amoeba_net.py
models/experimental/amoeba_net/amoeba_net_model.py
models/experimental/amoeba_net/model_builder.py
models/experimental/cifar_keras/cifar_keras.py
models/experimental/dcgan/dcgan_main.py
models/experimental/inception/inception_v2.py
models/experimental/inception/inception_v3.py
models/experimental/inception/inception_v3_old.py
models/experimental/inception/inception_v4.py
models/experimental/keras/imagenet_input.py
models/experimental/keras/mnist.py
models/experimental/keras/resnet50.py
models/experimental/keras/resnet_preprocessing.py
models/experimental/resnet_bfloat16/resnet_benchmark.py
models/experimental/resnet_bfloat16/resnet_main.py
models/official/densenet/densenet_imagenet.py
models/official/mobilenet/mobilenet.py
models/official/resnet/benchmark/resnet_benchmark.py
models/official/resnet/resnet_main.py
models/official/retinanet/retinanet_main.py
models/official/retinanet/retinanet_model.py
models/official/squeezenet/squeezenet_main.py
models/official/squeezenet/squeezenet_model.py
tools/ctpu/tutorial.md

Merge internal changes into public repository (change 204930699)

---

google3/third_party/cloud_tpu/colab/shakespeare_with_tpu_and_keras.ipynb
models/official/resnet/imagenet_input.py
models/official/resnet/resnet_main.py
tools/ctpu/commands/up.go
tools/ctpu/commands/up_test.go

Merge internal changes into public repository (change )

---

tools/docker/Dockerfile.util
tools/kubernetes/tensorboard_k8s.yaml
tools/kubernetes/tpu_profiler_k8s.yaml

Add example YAMLs for running TensorBoard and TPU Profiler on GKE

---

models/experimental/inception/inception_v3_k8s.yaml
models/official/amoeba_net/amoeba_net_k8s.yaml
models/official/resnet/resnet_k8s.yaml
models/official/retinanet/retinanet_k8s.yaml
tools/datasets/download_and_preprocess_coco_k8s.yaml
tools/datasets/imagenet_to_gcs_k8s.yaml
tools/docker/Dockerfile
tools/docker/Dockerfile.util
tools/kubernetes/tensorboard_k8s.yaml
tools/kubernetes/tpu_profiler_k8s.yaml

Update Kubernetes examples to use TF 1.11 + new examples for TensorBoard and TPU Profiler.

---

tools/ctpu/commands/up.go
tools/ctpu/commands/up_test.go

Add -tpu-only flag to ctpu

---

models/samples/core/get_started/custom_tpuestimator.py
models/samples/core/get_started/iris_data_tpu.py

Adding sample classification model running on TPU using TPUEstimator. This model is using iris dataset.
This will be shared with external customers via TPUEstimator Tutorial.

Merge internal changes into public repository (change 221197171)

---

google3/third_party/cloud_tpu/models/keras_application/application_model.py
models/common/imagenet.py
models/experimental/mask_rcnn/coco_metric.py
models/experimental/mask_rcnn/mask_rcnn_architecture.py
models/experimental/mask_rcnn/mask_rcnn_main.py
models/experimental/mask_rcnn/mask_rcnn_model.py
models/experimental/mask_rcnn/mask_rcnn_params.py
models/official/resnet/resnet_model.py
models/official/resnet/resnet_model_test.py

Hi Team,
This pull request is generated by Hongkun.

Merge internal changes into public repository (change 230661130)

---

models/experimental/mask_rcnn/box_utils.py
models/experimental/mask_rcnn/dataloader.py
models/experimental/mask_rcnn/heads.py
models/experimental/mask_rcnn/mask_rcnn_model.py
models/experimental/mask_rcnn/mask_rcnn_params.py
models/experimental/mask_rcnn/postprocess_ops.py
models/experimental/mask_rcnn/roi_ops.py
models/official/amoeba_net/amoeba_net.py
models/official/mnasnet/README.md
tools/colab/keras_mnist_tpu.ipynb

Changed the authentication cell with simplifications from Martin Gorner.

Merge internal changes into public repository (change 235069324)

---

tools/docker/Dockerfile

Add pyyaml dependency in Dockerfile

---

models/experimental/mask_rcnn/mask_rcnn_k8s.yaml

Adding Kubernetes Job specs for the Mask-RCNN model.

Merge internal changes into public repository (change 242588377)

---

models/experimental/detection/export_saved_model.py

TPU Estimator API was incompatible with r1.13.

Fix invalid export_saved_model for detection

---

models/experimental/mask_rcnn/mask_rcnn_k8s.yaml
tools/datasets/download_and_preprocess_coco_k8s.yaml

Changing the TF versions to 1.13 and adding mask_rcnn_k8s.yaml to branch 1.13.

Changing the TF versions to 1.13 and adding mask_rcnn_k8s.yaml to branch 1.13.

---

models/official/detection/main.py

Flag changes from params_overrides to params_override and giving an additional parameter config_file to add an additional layer of parameters overriding

R1.13: Flag changes from params_overrides to params_override

---

models/official/detection/dataloader/tf_example_decoder.py
models/official/efficientnet/README.md
models/official/efficientnet/edgetpu/README.md

Explicitly set the number of channels during image decoding.

Explicitly set the number of channels during image decoding.

---

models/official/efficientnet/main.py

Change use_cache to be False by default for EfficientNet.

---

tools/datasets/download_and_preprocess_coco_k8s.yaml

Updates to the Keras MNIST TPU colab to support TF 1.14.

Merge internal changes into public repository (change 252085935)

---

models/official/efficientnet/condconv/__init__.py
models/official/efficientnet/condconv/condconv_layers.py
models/official/efficientnet/condconv/condconv_layers_test.py

Internal changes.

---

models/experimental/qanet/data.py
models/official/detection/dataloader/input_reader.py
models/official/detection/evaluation/coco_utils.py
models/official/retinanet/dataloader.py

\nInternal refactor\n

---

models/official/mask_rcnn/object_detection/tf_example_decoder.py

Add back in optional keys for tf_example_decoder.py

---

models/official/mnasnet/mnas_utils.py

> import utils as efficientnet_utils
> ImportError: No module named utils

[fix] path error in mnasnet

---

models/official/efficientnet/preprocessing.py

"to be applied applied" -> "to be applied "

fix typo:repeat words

---

models/official/detection/evaluation/coco_evaluator.py
models/official/detection/evaluation/coco_utils.py

Python 3 compatibility changes.

---

models/official/detection/dataloader/retinanet_parser.py

 Merge internal changes into public repository.

---

models/experimental/deeplab/README.md

Update the flag multi_grid.

---

tools/datasets/download_and_preprocess_coco.sh

Python3 related changes in download script for COCO dataset.

---

models/experimental/inference/load_test_client.py

Fix for the Python3 related error.

---

models/official/detection/modeling/architecture/heads.py

  Internal changes

---

models/official/resnet/configs/resnet_config.py
models/official/resnet/resnet_layers.py
models/official/resnet/resnet_main.py
models/official/resnet/resnet_model.py
models/official/resnet/resnet_model_test.py

Introduce ResNet-RS to `cloud_tpu/official/models`.

---

models/official/detection/modeling/architecture/heads.py

Internal Sync

---

models/experimental/inference/load_test/data/data_loader.py
models/experimental/inference/load_test/data/data_loader_factory.py
models/experimental/inference/load_test/data/synthetic_bert.py
models/experimental/inference/load_test/data/synthetic_bert_test.py
models/experimental/inference/load_test/data/synthetic_image.py
models/experimental/inference/load_test/examples/loadgen_grpc_main.py
models/experimental/inference/load_test/examples/loadgen_grpc_main_test.py
models/experimental/inference/load_test/targets/grpc_target.py
models/experimental/inference/load_test/targets/grpc_target_test.py
models/experimental/inference/load_test/testing/mock_grpc.py
models/experimental/inference/load_test/traffic_handlers/loadgen_handler.py
models/experimental/inference/load_test/traffic_handlers/loadgen_handler_test.py

Changes:
- Added in a `synthetic_bert` data loader, integrated it into `data_loader` code.
- Modified the way targets process data such that it returns dictionaries with the input name as key and the payload as value.
- Some fixes for underlying LoadGen.
PiperOrigin-RevId: 382830365

Some load test changes for compatibility in OSS.

---

models/experimental/inference/load_test/tools/Dockerfile

Create Dockerfile for serving load testing tool.

---

models/experimental/inference/load_test/tools/Dockerfile

Add copyright header to Dockerfile, switch to google/sdk base.

---

tools/datasets/imagenet_to_gcs.py

Respectful code cleanup in `imagenet_to_gcs.py`

---

models/experimental/resnet50_keras/resnet50_ctl_tf2.py
models/official/detection/dataloader/tf_example_decoder.py
tools/driver/drivers/accel/accel.c

Internal change.

---

google3/third_party/cloud_tpu/opensource_only/grpc_tpu_worker/README.md
tools/grpc_tpu_worker/grpc_tpu_worker.py

Expose grpc_tpu_worker.py

---

tools/datasets/README.md

Revert "ImageNet labels file moved"

---

tools/kubernetes/terraform/examples/v4/main.tf
tools/kubernetes/terraform/examples/v4/outputs.tf
tools/kubernetes/terraform/examples/v4/terraform.tfvars
tools/kubernetes/terraform/examples/v5e/main.tf
tools/kubernetes/terraform/examples/v5e/outputs.tf
tools/kubernetes/terraform/examples/v5e/terraform.tfvars
tools/kubernetes/terraform/module/main.tf
tools/kubernetes/terraform/module/terraform.tfvars
tools/kubernetes/terraform/module/variables.tf

Brings back some terraform scripts that were accidentally deleted.

---

tools/kubernetes/terraform/examples/v5e/main.tf
tools/kubernetes/terraform/examples/v5e/terraform.tfvars
tools/kubernetes/terraform/module/main.tf
tools/kubernetes/terraform/module/outputs.tf
tools/kubernetes/terraform/module/terraform.tfvars
tools/kubernetes/terraform/module/variables.tf

- Update Terraform script for enabling image streaming and disabling auto upgrade.
- Update Terraform script to support compact placement policy name and introduce location var.

Update Terraform script to support compact placement policy name and introduce location var.

---

tools/kubernetes/terraform/examples/v5e/outputs.tf
tools/kubernetes/terraform/examples/v5e/terraform.tfvars
tools/kubernetes/terraform/module/outputs.tf

- Update Terraform script for enabling image streaming and disabling auto upgrade.
- Update Terraform script to support compact placement policy name and introduce location var.
- Update some flag values in the v5e example.
- Update the output information.

Update example flag values and output information.

---

tools/kubernetes/terraform/module/main.tf

- Add a new scope for cloud-platform.
- Update Terraform script to enable vpc-native traffic routing.

Update Terraform script to enable vpc-native traffic routing.

---

tools/kubernetes/terraform/examples/v5e/terraform.tfvars
tools/kubernetes/terraform/module/main.tf
tools/kubernetes/terraform/module/variables.tf

Revert "Override boot-disk type and size for v5e node"

---

tools/driver/drivers/accel/accel.c
tools/driver/drivers/asic_sw/asic_fw_device_owner_accessor.h
tools/driver/drivers/asic_sw/asic_fw_indirect_accessor.h
tools/driver/drivers/gasket/gasket_core.c
tools/driver/drivers/gasket/gasket_dmabuf.c
tools/driver/drivers/gasket/gasket_page_table.c

Make TPU v4 kernel drivers compatible with linux kernel 6.2.
